### ISSUE TITLE
Strips inline elements

### ISSUE THREAD

**Issue by cdCorey** [freqdec/slabText#39]
I'm working on a design that is supposed to have a line of large responsive text where the second part of the line is slightly smaller than the rest. I tried wrapping the whole thing in a span.slabtext and then wrapping the second part in span.smaller (styled to 90% font-size). Seems like this should be the right way to accomplish this, however, for some reason the nested span gets stripped out by slabText. I can't see any reason why that needs to happen -- at least not when the span.slabtext is pre-applied. Is it possible this could be fixed?

I'm using it on one line of text, so I could probably use FitText instead, but I'd rather stick with slabText because it's more versatile. I'd feel rather silly if I end up needing to use two different text fitting scripts.

**Comment by jevets** [comment]
Had the same issue, but I eventually fixed by wrapping the elements in a parent and calling `slabText()` on the parent. I.e. 

```html
<div class="slab-this-text">
  <span class="slabtext">Some text is <span class="special-class">Special</span></span>
</div>
```

```js
$('.slab-this-text').slabText();
```

**Comment by cdCorey** [comment]
Good to know. That will be a useful workaround if I run into this issue again in the future.
