### ISSUE TITLE
"Please do not do this in a production environment"

### ISSUE THREAD

**Issue by sogen** [freqdec/slabText#40]
Hi, what's the recommended use for a production environment (intranet)?
In issue #31 you mention using ```("#someElem").show().slabText()``` to reduce JS overhead

I'm only using local webfonts files (no internet, no loading of Google Fonts)

thx :+1:

**Comment by freqdec** [comment]
The demo has been updated to use google font loader. You can always fallback to the onload event if a webfont loader isn't available
