### ISSUE TITLE
Doesn't work on input type submit

### ISSUE THREAD

**Issue by LandingOnJupiter** [freqdec/slabText#42]
Applying slabText to an HTML form's submit button doesn't work. Example: 
`<input type="submit" value="Click Me!" name="submit" id="submit-button" />`

I realize I can work around it with `<button>Click Me!</button>` or `<a class='button' href='example.com'>Click Me!</a>` and triggering the submit via jQuery. But, if a plugin is generating the submit button, I may not have the ability to do that.

**Comment by freqdec** [comment]
Hi, the script needs text nodes to resize. These aren't available with input form elements (but are with button).
