### ISSUE TITLE
done callback?

### ISSUE THREAD

**Issue by twmulloy** [freqdec/slabText#46]
a nice feature to have would be if `slabText` returned a promise that could be used to trigger other events after it is done processing texts.

```
var slabtext = $('h1').slabtext();
slabtext.then(function(){
  // trigger some other update function 
  // such as div resize to accommodate for div dimension changes made by slabtext
});

**Comment by freqdec** [comment]
I would only use promises in an async situation. Probably a bit overkill here. I've added a simple "onRender" callback that gets executed every time the header is recalculated.
